import { Inter } from 'next/font/google'
import './globals.css'
import { Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const popins =Poppins ({
  weight:"700",
  subsets:['latin'],
  variable:"--cinzel"
    }
  )
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={ popins.className}>{children}</body>
    </html>
  )
}
