import { Inter } from 'next/font/google'
import './globals.css'
import { Poppins } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
const popins =Poppins ({
  weight:"800",
  subsets:['latin'],
  variable:"--cinzel"
    }
  )
  const popins1 =Poppins ({
    weight:"300",
    subsets:['latin'],
    variable:"--cinzel1"
      }
    )
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={ `${popins.variable}`}>
      <body  className={`${popins1.variable}`}>{children}</body>
    </html>
  )
}
